### ISSUE TITLE
Update 6.x->7.1.0, Typo3 v11.5: dysfunctional blog backend module - type error in logic inside extension

### ISSUE THREAD

**Issue by UmbrellaDish** [fnagel/t3extblog#259]
> Type Error (1/1)
>
>  Return value of FelixNagel\T3extblog\Domain\Model\PostSubscriber::getPost() must be an instance of FelixNagel\T3extblog\Domain\Model\Post, null returned
>
> [Stack trace following, innermost i.e. top frame in /web/propylaeum/htdocs/public/typo3conf/ext/t3extblog/Classes/Domain/Model/PostSubscriber.php line 108. Tree of pages and and list of modules shown left alright.]

I (believe at least I) fixed pagination so the extension renders blog pages all fine in the frontend. We followed the, if you don't mind my saying, a bit short and summarizing Upgrade guideline in the documentation (Upgrade to 7.0.0). For sure chances are I have just forgotten something but I fail to deduce from the error what is missing. I tried to check that all blog configuration included in our site package extension is up-to-date, but let's include the relevant YAML code here for the sake of completeness, even if it seems to relate to frontend logic, too:

```yaml
    routes:
      - routePath: '/'
        _controller: 'Subscriber::list'
      - routePath: '/logout'
        _controller: 'Subscriber::logout'
      - routePath: '/error'
        _controller: 'Subscriber::error'
      - routePath: '/post/confirm/{subscription_code}'
        _controller: 'PostSubscriber::confirm'
        _arguments:
          'subscription_code': 'code'
      - routePath: '/post/list/{subscription_code}'
        _controller: 'PostSubscriber::list'
        _arguments:
          'subscription_code': 'code'
      - routePath: '/post/delete/{subscription_uid}'
        _controller: 'PostSubscriber::delete'
        _arguments:
          'subscription_uid': 'subscriber'
```

We use Typo3 in composer mode, if that is relevant in a way.
